language: java
dist: xenial
jdk: openjdk8
before_install:
    - cd vilebot/
    - bash download-fonts.sh
    - cd ../
    - cp vilebot/cfg/vilebot.conf.example vilebot/cfg/vilebot.conf
install: true
script: mvn verify
